const Introduction = () => {
  return (
    <div>
      <p>
        CatsOnChain is the first 100% On-Chain generated GIF-collection on the
        Ethereum blockchain.
      </p>
      <p>
        Each NFT is a unique, animated cats (GIFs) Each cat is randomly
        generated by the Smart Contract when you mint
      </p>
      <p>
        You can mint on the smart contract. Check out the Medium-Post for more
        information.
      </p>
    </div>
  );
};

export default Introduction;
