import "./Info.css";

const Info = () => {
  return (
    <div className="info textBox ">
      <h1>About this project</h1>
      <p className="text">
        Some important information about the project:
        <ul>
          <li>100% On-Chain in just one</li>
          <li>
            Smart Contract on the Ethereum Blockchain 11,111 unique, animated
            cats
          </li>
          <li>
            (GIFs) Each cat will be randomly generated by the Smart Contract
            when
          </li>
          <li>you mint You can just mint directly on the smart contract</li>
        </ul>
      </p>
    </div>
  );
};

export default Info;
