import TextDecorator from "../text-decorator/TextDecorator";
import "./Info.css";

const Info = () => {
  return (
    <div className="info textBox ">
      <h1><TextDecorator>About this project</TextDecorator></h1>
      <p className="text">
        Some important information about the project:
        </p>

        <ul className="text">
          <li>
            100% On-Chain in just one Smart Contract on the Ethereum Blockchain
          </li>
          <li>11,111 unique, animated cats (GIFs)</li>
          <li>
            Each cat will be randomly generated by the Smart Contract when you
            mint
          </li>
          <li> You can just mint directly on the smart contract; minting will be implemented on this site in the future</li>
        </ul>
    </div>
  );
};

export default Info;
